import React from 'react';
import './App.css';
import './SASSStyles.scss';
import SoundGraph from './components/SoundGraph';
import swal from "sweetalert";

function App() {

  const showHelp = () => swal({
    title: 'Designing Sounds by Drawing Them',
    className: 'instructions',
    text: `
    Sound mode or Amplitude mode: Choose on which wave to operate on.

    Resample graph: Sample a new wave from the specified points.

    Reset graph: Delete the selected wave.

    Play: In Sound mode, play the sound generated by the sound mode wave. In Amplitude mode, play the sound wave which is amplidute modulated by the amplitude mode wave.
    
    Pause: Pause the sound.
    
    Download: Download the sound that would normally be played should you press Play.
    
    X-Axis Range: TODO 
    
    Kernels: Choose which kernel to use for generating the wave. You can tweak the parameters yourself, or optimise them automatically.
    
    You can reopen this prompt at any time using the '?' button.
    `,
    closeOnClickOutside: true,
    closeOnEsc: true,
});

  showHelp();
  return  (
    <div>
      <div className="helpBox">
        <button onClick={showHelp} className="help">?</button>
      </div>
      <SoundGraph />
    </div>
  )
}
export default App;